###
@url = http://localhost:8000
@basicToken = Zm9vOmJhcg==
###
GET {{url}}/rustaceans
Authorization: Basic {{basicToken}}
###
GET {{url}}/rustaceans/1
Authorization: Basic {{basicToken}}
###
GET {{url}}/rustacHeans/1
Authorization: Basic {{basicToken}}
###
GET {{url}}/rustaceans/asd
Authorization: Basic {{basicToken}}
###
POST {{url}}/rustaceans
Content-Type: application/json
Authorization: Basic {{basicToken}}

{
  "name": "John Doe",
  "email": "sdasdas@dasdasd.com"
}
###
PUT {{url}}/rustaceans/1
Content-Type: application/json
Authorization: Basic {{basicToken}}

{
  "name": "John Doe",
  "email": "sdasdas@dasdasd.com"
}
###
DELETE {{url}}/rustaceans/1
Authorization: Basic {{basicToken}}
